---

- name: DevStack setup for OpenStack development
  hosts: all
  become: true
  vars:
    devstack_user_name: 'stack'
    devstack_user_home: '/opt/stack'
    devstack_user_shell: '/bin/bash'

    devstack_repo_url: 'https://opendev.org/openstack/devstack.git'
    devstack_repo_branch: 'master'
    devstack_repo_depth: 1

    devstack_install_dir: '{{ devstack_user_home }}/devstack'

    devstack_lvm_vg_name: 'devstack'
    devstack_lvm_vg_size: 30G
    devstack_lvm_be_name: 'lvmdriver-1'
    devstack_lvm_lv_prefix: 'volume-'

    devstack_services_enabled:
      # keystone services
      - 'keystone'
      # nova services with SPICE support
      - 'nova'
      - 'n-spice'
      # placement services for nova
      - 'placement'
      # glance services
      - 'glance'
      # cinder services
      - 'cinder'
      # network services
      - 'neutron'
      # dashbord services
      - 'horizon'
    devstack_services_disabled:
      # nova services with VNC support
      - 'n-novnc'

    devstack_svc_cinder_backends_enabled:
      - 'lvm:{{ devstack_lvm_be_name }}'
    devstack_svc_cinder_img_cache_enabled: false

    devstack_setup_pw_admin: devstack
    devstack_setup_pw_database: devstack
    devstack_setup_pw_rabbit: devstack
    devstack_setup_pw_service: devstack

  tasks:
    - name: Install required dependencies
      ansible.builtin.package:
        name:
          - python3
          - git
          - acl
        state: present

    - name: Create user '{{ devstack_user_name }}' for DevStack setup
      ansible.builtin.user:
        name: '{{ devstack_user_name }}'
        create_home: true
        home: '{{ devstack_user_home }}'
        shell: '{{ devstack_user_shell }}'

    - name: Grant root privileges to user '{{ devstack_user_name }}'
      ansible.builtin.copy:
        dest: '/etc/sudoers.d/{{ devstack_user_name }}'
        content: |
          {{ devstack_user_name }} ALL=(ALL) NOPASSWD: ALL
        owner: root
        group: root
        mode: '0440'

    - name: Clone DevStack Git repository
      become_user: '{{ devstack_user_name }}'
      become: true
      ansible.builtin.git:
        repo: '{{ devstack_repo_url }}'
        version: '{{ devstack_repo_branch }}'
        dest: '{{ devstack_install_dir }}'
        depth: '{{ devstack_repo_depth }}'

    - name: Configure DevStack setup
      become_user: '{{ devstack_user_name }}'
      become: true
      ansible.builtin.template:
        src: 'devstack_local.conf.j2'
        dest: '{{ devstack_install_dir }}/local.conf'
        owner: '{{ devstack_user_name }}'
        group: '{{ devstack_user_name }}'
        mode: '0644'
      register: output_devstack_create_config

    - name: Setup DevStack
      become_user: '{{ devstack_user_name }}'
      become: true
      ansible.builtin.shell:
        chdir: '{{ devstack_install_dir }}'
        cmd: |
          GIT_DEPTH="{{ devstack_repo_depth }}"
          ./stack.sh
      when: output_devstack_create_config.changed
